### ISSUE TITLE
configureMailUrl is not a function

### ISSUE THREAD

**Issue by owenhoskins** [reactioncommerce/reaction-inventory#1]
On password reset getting:

`Reactioncommerce_reaction-accounts.js:3595 Uncaught TypeError: ReactionCore.configureMailUrl is not a function`

running development branch of
`````
reactioncommerce:bootstrap-theme@1.7.0
reactioncommerce:core@0.9.5
reactioncommerce:core-theme@1.8.0
reactioncommerce:reaction-accounts@1.5.2
reactioncommerce:reaction-analytics@1.2.0
reactioncommerce:reaction-analytics-libs@1.1.0
reactioncommerce:reaction-inventory@0.1.0
reactioncommerce:reaction-social@0.4.1
reactioncommerce:reaction-stripe@3.0.1
``````

**Comment by aaronjudd** [comment]
@mikemurray I think this probably is an issue with https://github.com/reactioncommerce/reaction-accounts (probably could just move this issue over there, but this probably is an easy fix).
